### ISSUE TITLE
Compiled workflow link in README is broken

### ISSUE THREAD

**Issue by janclarin** [wkoffel/alfred-terminal-control#2]
Getting a 404 when clicking on the link in the README:
"Download the compiled workflow directly at https://github.com/wkoffel/alfred-terminal-control/raw/master/alfredworkflow/Terminal%20Control.alfredworkflow"

The `.alfredworkflow` file is not in the repo.

**Comment by wkoffel** [comment]
Fixed with a new `dist` directory at https://github.com/wkoffel/alfred-terminal-control/tree/master/dist where I'll keep new builds moving forward.  Good suggestion from @janclarin

**Comment by janclarin** [comment]
No problem. I've been looking for an Alfred workflow to open a directory in the terminal, so this helped me a ton. Thank you.
