### ISSUE TITLE
No dist folder

### ISSUE THREAD

**Issue by alexreg** [wkoffel/alfred-terminal-control#4]
There's no dist folder, and the install link in the README is thus broken. Is the pre-compiled workflow available anywhere?

**Comment by wkoffel** [comment]
Thanks @alexreg for reporting this.  I had inadvertently deleted it in a recent update.  I've restored the dist folder, with recent builds.

For future folks checking these threads, I also generally keep the alfred forum post up to date with the latest links to binaries too: https://www.alfredforum.com/topic/2334-terminal-control-workflow/

**Comment by alexreg** [comment]
Okay, thanks @wkoffel.
